#!/bin/bash

echo "➜ Ignore Permission Changes"
git config core.fileMode false

echo "➜ Set Correct Permissions"
chmod -R 777 storage

echo "➜ Install Composer Dependencies"
[[ -d vendor ]] || composer install

echo "➜ Install NPM Dependencies"
[[ -d node_modules ]] || npm install

echo "➜ Build Project Assets"
[[ -d assets/vendor ]] || npx gulp compile

echo "➜ Waiting for MySQL to be ready"
/usr/local/bin/wait-for-mysql.sh

if [ $? -eq 0 ]; then
  echo "➜ MySQL is ready. Starting backup."
  /usr/local/bin/backup.sh
else
  echo "➜ MySQL is not ready. Backup skipped."
fi

echo "➜ Listening to incoming requests"
php-fpm